theme: jekyll-theme-architect
plugins:
  - jemoji
exclude:
  - README.md
title: rika's page
description: [A short description of your site's purpose]
# url definitions
header_page_refs: ['about', 'slides']
